app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('upload/{id}/step_2', 'GifUploadController@uploadStepTwo');
Route::post('upload/{id}/store_step_2', 'GifUploadController@storeStepTwo');
Route::get('upload/{id}/step_3', 'GifUploadController@uploadStepThree');
Route::post('upload/{id}/store_step_3', 'GifUploadController@storeStepThree');
Route::get('upload/{id}/step_4', 'GifUploadController@uploadStepFour');
Route::post('upload/{id}/store_step_4', 'GifUploadController@storeStepFour');
Route::get('upload/{id}/finalize', 'GifUploadController@uploadFinalize');
Route::post('upload/{id}/store_step_5', 'GifUploadController@storeStepFive');
Route::get('upload/{id}/step_5', 'GifUploadController@uploadStepFive');
Route::post('upload/{id}/store_step_6', 'GifUploadController@storeStepSix');
Route::get('upload/{id}/step_6', 'GifUploadController@uploadStepSix');
Route::resource('upload', 'GifUploadController');



Route::resource('/', 'GifController');

Route::get('gifs/{directory}/{filename}', function ($directory, $filename)
{
    $path = storage_path() . '/app/gifs/' . $directory . '/' .$filename;
    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('images/{directory}/{filename}', function ($directory, $filename)
{
    $path = storage_path() . '/app/images/' . $directory . '/' .$filename;
    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});


/**
 * Services
 */
$this->app->bind('FileUploadHandler', function ($app) {
    return new App\Handler\FileUploadHandler(
        new App\Handler\FrameSplitter()
    );
});

$this->app->bind('FrameJoiner', function($app) {
   return new App\Handler\FrameJoiner();
});

resources/views/upload/finalize.blade.php
@extends('app')

@section('content')
    @parent
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Upload Image</h3>
        </div>
        <div class="panel-body">
            <form id="step_4_form" action="/upload/{{$gif->id}}/store_step_4" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="row">
                        <div class="col-md-6">
                            <label>Your Fresh Gif:</label>
                            <img id="gif_{{$gif->id}}" src="/gifs/{{$gif->path}}/completed.gif"/>
                        </div>
                </div>
                <div class="row">
                    <div class="form-group pull-right">
                        <div class="col-md-2 offset-2">
                            <input type="submit" class="btn btn-lg btn-default" value="OKAY JABRONI"/>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script type="text/javascript">

        var canvas_obj =  {
            onReady: function() {
                var canvas = $('.image_canvas');
                canvas.each(function(i) {
                    var ctx = this.getContext('2d');
                    var img = document.createElement('IMG');
                    var image_id = this.id;
                    var related_image = $('#image_'+image_id);

                    img.onload = function() {
                        var OwnCanv = new fabric.Canvas(image_id, {
                            isDrawingMode: true
                        });

                        var imgInstance = new fabric.Image(img, {
                            left: 0,
                            top: 0
                        });
                        OwnCanv.add(imgInstance);

                        OwnCanv.freeDrawingBrush.color = "transparent";
                        OwnCanv.freeDrawingBrush.width = 4;

                        OwnCanv.on('path:created', function(options) {
                            var path = options.path;
                            OwnCanv.isDrawingMode = false;
                            OwnCanv.remove(imgInstance);
                            OwnCanv.remove(path);
                            OwnCanv.clipTo = function(ctx) {
                                path.render(ctx);
                            };
                            OwnCanv.add(imgInstance);
                        });

                        //saves our modified base64 image to an input
                        OwnCanv.on('mouse:up', function(e) {
                            var img = this.toDataURL('image/png');
                            $("#modified_image").val(img);
                        });
                    };

                    img.src = related_image.attr('src');
                })
            }
        };

        var form_handler = {
            onSubmit: function(e) {
                e.preventDefault();
            }
        };

        $(document).ready(canvas_obj.onReady);
        $(document).click(canvas_obj.onMouseUp);
        //$(document).submit(form_handler.onSubmit);
    </script>
@endsection

resources/views/upload/index.blade.php
@extends('app')

@section('content')
    @parent
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Upload Gif</h3>
        </div>
        <div class="panel-body">
            <form action="{{route('upload.store')}}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="gif" class="form-control">Upload a Gif</label>
                    <input required type="file" name="gif" class="form-control">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-lg btn-default" value="upload">
                </div>
            </form>
          </div>
    </div>
@endsection

resources/views/upload/show.blade.php
@extends('app')

@section('content')
    @parent
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Modify Gif</h3>
        </div>
        <div class="panel-body">
            <form>
                <div class="row">
                    @foreach($gif->frames()->get() as $frame)
                        <div class="col-lg-4">
                            <canvas id="{{$frame->id}}" width="320px" height="270px" class="frame_canvas"></canvas>
                            <img id="image_{{$frame->id}}" class="hidden" src="/images/{{$frame->gif->name}}/{{$frame->name}}"/>
                            <input id="frame_coords_{{$frame->id}}" type="hidden" name="frame_coords[{{$frame->id}}]"/>
                        </div>
                    @endforeach
                </div>
                <div class="row">
                    <div class="form-group">
                        <input type="submit" class="btn btn-lg btn-default" value="Next"/>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script type="text/javascript">

        function getMousePos(canvas, evt) {
            var rect = canvas.getBoundingClientRect();
            return {
                x: evt.clientX - rect.left,
                y: evt.clientY - rect.top
            };
        }

        var canvas_obj =  {
            onReady: function() {
                var frame_canvas = $('.frame_canvas');
                frame_canvas.each(function(i) {
                    var context = this.getContext('2d');
                    var imageObj = new Image();
                    var frame_id = $(this).attr('id');
                    var related_image = $('#image_'+frame_id);

                    imageObj.onload = function() {
                        context.drawImage(imageObj,0, 10);
                    };
                    imageObj.src = related_image.attr('src');

                    this.addEventListener('click', function(evt) {
                        frame_id = $(this).attr('id');
                        var mousePos = getMousePos(this, evt);
                        var coords  = mousePos.x + ',' + mousePos.y;
                        context.fillStyle = "#FF0000";
                        context.beginPath();
                        context.arc(mousePos.x, mousePos.y, 25, 0, 2*Math.PI);
                        context.fill();
                        $('#frame_coords_'+frame_id).val(coords);
                    }, false);
                })
            },
        };

        $(document).ready(canvas_obj.onReady);

    </script>
@endsection

resources/views/upload/upload_step_five.blade.php
@extends('app')

@section('content')
    @parent
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Crop Image</h3>
        </div>
        <div class="panel-body">
            <form id="step_5_form" action="/upload/{{$gif->id}}/store_step_5" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="row">
                        <div class="col-md-6">
                            <label>{{$image->name}}</label>
                                <img id="crop_image" width="320px" height="240px" src="/images/{{$image->path}}/{{$image->name}}"/>
                        </div>
                        <div class="col-md-6">
                            <img id="preview"/>
                        </div>
                </div>
                <div class="row">
                    <div class="form-group pull-right">
                        <div class="col-md-2 offset-2">
                            <input id="x" type="hidden" name="x"/>
                            <input id="w" type="hidden" name="w"/>
                            <input id="y" type="hidden" name="y"/>
                            <input id="h" type="hidden" name="h"/>
                            <input id="x2" type="hidden" name="x2"/>
                            <input id="y2" type="hidden" name="y2"/>
                            <input type="submit" class="btn btn-lg btn-default" value="Ready to Work"/>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script type="text/javascript">

        $(function(){
            // for sample 1
            $('#crop_image').Jcrop({ // we linking Jcrop to our image with id=cropbox1
                aspectRatio: 0,
                onChange: updateCoords,
                onSelect: updateCoords
            });

            var i, ac;

            // A handler to kill the action
            function nothing(e) {
                e.stopPropagation();
                e.preventDefault();
                return false;
            };

            // Returns event handler for animation callback
            function anim_handler(ac) {
                return function(e) {
                    api.animateTo(ac);
                    return nothing(e);
                };
            };

            // Setup sample coordinates for animation
            var ac = {
                anim1: [0,0,40,600],
                anim2: [115,100,210,215],
                anim3: [80,10,760,585],
                anim4: [105,215,665,575],
                anim5: [495,150,570,235]
            };

            // Attach respective event handlers
            for(i in ac) jQuery('#'+i).click(anim_handler(ac[i]));

        });

        function updateCoords(c) {
            $('#x').val(c.x);
            $('#y').val(c.y);
            $('#w').val(c.w);
            $('#h').val(c.h);

            $('#x2').val(c.x2);
            $('#y2').val(c.y2);

            var rx = 200 / c.w; // 200 - preview box size
            var ry = 200 / c.h;

            /*
            $('#preview').css({
                width: Math.round(rx * 800) + 'px',
                height: Math.round(ry * 600) + 'px',
                marginLeft: '-' + Math.round(rx * c.x) + 'px',
                marginTop: '-' + Math.round(ry * c.y) + 'px'
            });
            */
        };

        function checkCoords() {
            if (parseInt($('#w').val())) return true;
            alert('Please select a crop region then press submit.');
            return false;
        };

    </script>
@endsection

resources/views/upload/upload_step_four.blade.php
@extends('app')

@section('content')
    @parent
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Upload Image</h3>
        </div>
        <div class="panel-body">
            <form id="step_4_form" action="/upload/{{$gif->id}}/store_step_4" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="row">
                    @foreach($gif->images()->get() as $image)
                        <div class="col-md-6">
                            <label>Original:</label>
                            <canvas id="{{$image->id}}" width="320px" height="240px" class="image_canvas"></canvas>
                            <img id="image_{{$image->id}}" class="hidden" src="/images/{{$image->path}}/{{$image->name}}"/>
                            <input type="hidden" id="modified_image" name="modified_image" />
                        </div>
                    @endforeach
                </div>
                <div class="row">
                    <div class="form-group pull-right">
                        <div class="col-md-2 offset-2">
                            <input type="submit" class="btn btn-lg btn-default" value="Ready to Work"/>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script type="text/javascript">

        var canvas_obj =  {
            onReady: function() {
                var canvas = $('.image_canvas');
                canvas.each(function(i) {
                    var ctx = this.getContext('2d');
                    var img = document.createElement('IMG');
                    var image_id = this.id;
                    var related_image = $('#image_'+image_id);

                    img.onload = function() {
                        var OwnCanv = new fabric.Canvas(image_id, {
                            isDrawingMode: true
                        });

                        var imgInstance = new fabric.Image(img, {
                            left: 0,
                            top: 0
                        });
                        OwnCanv.add(imgInstance);

                        OwnCanv.freeDrawingBrush.color = "transparent";
                        OwnCanv.freeDrawingBrush.width = 4;

                        OwnCanv.on('path:created', function(options) {
                            var path = options.path;
                            OwnCanv.isDrawingMode = false;
                            OwnCanv.remove(imgInstance);
                            OwnCanv.remove(path);
                            OwnCanv.clipTo = function(ctx) {
                                path.render(ctx);
                            };
                            OwnCanv.add(imgInstance);
                        });

                        //saves our modified base64 image to an input
                        OwnCanv.on('mouse:up', function(e) {
                            var img = this.toDataURL('image/png');
                            $("#modified_image").val(img);
                        });
                    };

                    img.src = related_image.attr('src');
                })
            }
        };

        var form_handler = {
            onSubmit: function(e) {
                e.preventDefault();
            }
        };

        $(document).ready(canvas_obj.onReady);
        $(document).click(canvas_obj.onMouseUp);
        //$(document).submit(form_handler.onSubmit);
    </script>
@endsection

resources/views/upload/upload_step_six.blade.php
@extends('app')
@section('stylesheets')
    @parent
    <style>
    </style>
@endsection

@section('content')
    @parent
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">ReSize Image</h3>
        </div>
        <div class="panel-body">
            <form id="step_6_form" action="/upload/{{$gif->id}}/store_step_6" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="row">
                    <div class="col-md-4">
                        <div id="draggable" style="display:inline-block">
                            <img id="resize_image" src="/images/{{$image->path}}/{{$image->name}}" style="z-index:100"/>
                        </div>
                    </div>
                    <div class="col-md-4" style="z-index:1">
                        <img id="reference_frame" src="/gifs/{{$gif->path}}/frame_000.png">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group pull-right">
                        <div class="col-md-2 offset-2">
                            <input id="width" type="hidden" name="width" value="150">
                            <input id="height" type="hidden" name="height" value="125">
                            <input type="submit" class="btn btn-lg btn-default" value="ZUG ZUG"/>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script type="text/javascript">
        var reposition = '';
        $(function(){
            $("#draggable").draggable();
            $( "#resize_image" ).resizable();

            $('#step_6_form').on("submit", function(e) {
                e.preventDefault();
                var img = document.getElementById('resize_image');
                var width = img.clientWidth;
                var height = img.clientHeight;

                $('#width').val(width);
                $('#height').val(height);
                this.submit();
            });
        });
    </script>
@endsection

resources/views/upload/upload_step_three.blade.php
@extends('app')

@section('content')
    @parent
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Upload Image</h3>
        </div>
        <div class="panel-body">
            <form action="/upload/{{$gif->id}}/store_step_3" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="row">
                    <div class="col-md-6 offset-2">
                        <div class="form-group">
                            <label for="image">Upload an Image</label>
                            <input type="file" REQUIRED name="image" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group pull-right">
                        <div class="col-md-2 offset-2">
                            <input type="submit" class="btn btn-lg btn-default" value="Next"/>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script type="text/javascript">

        function getMousePos(canvas, evt) {
            var rect = canvas.getBoundingClientRect();
            return {
                x: evt.clientX - rect.left,
                y: evt.clientY - rect.top
            };
        }

        var canvas_obj =  {
            onReady: function() {
                var frame_canvas = $('.frame_canvas');
                frame_canvas.each(function(i) {
                    var context = this.getContext('2d');
                    var imageObj = new Image();
                    var frame_id = $(this).attr('id');
                    var related_image = $('#image_'+frame_id);

                    imageObj.onload = function() {
                        context.drawImage(imageObj,0, 10);
                    };
                    imageObj.src = related_image.attr('src');

                    this.addEventListener('click', function(evt) {
                        frame_id = $(this).attr('id');
                        var mousePos = getMousePos(this, evt);
                        var coords  = mousePos.x + ',' + mousePos.y;
                        context.fillStyle = "#FF0000";
                        context.beginPath();
                        context.arc(mousePos.x, mousePos.y, 25, 0, 2*Math.PI);
                        context.fill();
                        $('#frame_coords_'+frame_id).val(coords);
                    }, false);
                })
            },
        };

        $(document).ready(canvas_obj.onReady);

    </script>
@endsection

resources/views/upload/upload_step_two.blade.php
@extends('app')

@section('content')
    @parent
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Modify Gif</h3>
        </div>
        <div class="panel-body">
            <form action="/upload/{{$gif->id}}/store_step_2" method="POST">
                {{csrf_field()}}
                <div class="row">
                    @foreach($gif->frames()->get() as $frame)
                        <div class="col-lg-4"">
                            <canvas id="{{$frame->id}}" width="320px" height="240px" class="frame_canvas" style="border:2px solid #cccccc"></canvas>
                            <img id="image_{{$frame->id}}" class="hidden" src="/gifs/{{$frame->gif->path}}/{{$frame->name}}"/>
                            <input id="frame_coords_{{$frame->id}}" type="hidden" name="frame_coords[{{$frame->id}}]"/>
                        </div>
                    @endforeach
                </div>
                <div class="row">
                    <div class="form-group pull-right">
                        <div class="col-md-2 offset-2">
                            <input type="submit" class="btn btn-lg btn-default" value="Next"/>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script type="text/javascript">

        function getMousePos(canvas, evt) {
            var rect = canvas.getBoundingClientRect();
            return {
                x: evt.clientX - rect.left,
                y: evt.clientY - rect.top
            };
        }

        var canvas_obj =  {
            onReady: function() {
                var frame_canvas = $('.frame_canvas');
                frame_canvas.each(function(i) {
                    var context = this.getContext('2d');
                    var imageObj = new Image();
                    var frame_id = $(this).attr('id');
                    var related_image = $('#image_'+frame_id);

                    imageObj.onload = function() {
                        context.drawImage(imageObj,0, 10);
                    };
                    imageObj.src = related_image.attr('src');

                    this.addEventListener('click', function(evt) {
                        frame_id = $(this).attr('id');
                        var mousePos = getMousePos(this, evt);
                        var coords  = mousePos.x + ',' + mousePos.y;
                        context.fillStyle = "#FF0000";
                        context.beginPath();
                        context.arc(mousePos.x, mousePos.y, 10, 0, 2*Math.PI);
                        context.fill();
                        $('#frame_coords_'+frame_id).val(coords);
                    }, false);
                })
            },
        };

        $(document).ready(canvas_obj.onReady);

    </script>
@endsection